import FourierSeriesSpecialOrthogonalFunctionsCanonicalLaneLean.AdmissibleClass
import FourierSeriesSpecialOrthogonalFunctionsCanonicalLaneLean.BridgeLemmas
import FourierSeriesSpecialOrthogonalFunctionsCanonicalLaneLean.GateLemmas
import FourierSeriesSpecialOrthogonalFunctionsCanonicalLaneLean.FinalTheorem
import FourierSeriesSpecialOrthogonalFunctionsCanonicalLaneLean.OrthogonalPolynomialSystem
import FourierSeriesSpecialOrthogonalFunctionsCanonicalLaneLean.FourierExpansionConvergence
import FourierSeriesSpecialOrthogonalFunctionsCanonicalLaneLean.SpecialFunctionTransform

namespace HautevilleHouse
namespace FourierSeriesSpecialOrthogonalFunctionsCanonicalLaneLean

-- Root module: imports all domain modules

end FourierSeriesSpecialOrthogonalFunctionsCanonicalLaneLean
end HautevilleHouse